// priority: 1

EntityEvents.checkSpawn("biomemakeover:blightbat", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:glowfish", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:mushroom_trader", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:scuttler", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:ghost", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:cowboy", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:decayed", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:tadpole", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:toad", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:lightning_bug", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:lightning_bug_alternate", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:rootling", e => e.success(false))
EntityEvents.checkSpawn("biomemakeover:helmit_crab", e => e.success(false))