
[types]

	[types.wood_type]

		[types.wood_type.biomebackport]
			cherry = true

		[types.wood_type.biomemakeover]
			blighted_balsa = false
			willow = false
			swamp_cypress = false
			ancient_oak = true

	[types.leaves_type]

		[types.leaves_type.biomebackport]
			cherry = true

		[types.leaves_type.biomemakeover]
			blighted_balsa = true
			willow = true
			swamp_cypress = true
			ancient_oak = true

[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			bookshelf = true
			boards = true
			ladder = true
			beehive = true
			trapped_chest = true
			chest = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.another_furniture]
			table = true
			shelf = true
			drawer = true
			shutter = true
			planter_box = true
			bench = true
			chair = true

		[entries.wood_type.campchair]
			camp_chair = true

	[entries.leaves_type]

		[entries.leaves_type.woodworks]
			leaf_pile = true

