placeSnowInBlock = true
placeSnowInBlockNaturally = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = true
snowAccumulationMaxLayers = 3
thinnerBoundingBox = true
snowMakingIce = true
snowNeverMelt = false
snowAndIceMeltInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = true
mobSpawningMaxLayers = 5

[integration]
accumulationWinterOnly = true

[debug]
weatherTickSlowness = 16
mobSpawningCommand = false
